module.exports = {
  apps: [
    {
      name: 'rally-staff',
      cwd: './apps/staff',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3001',
      instances: 4,
      exec_mode: 'cluster',
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/staff-error.log',
      out_file: './logs/staff-out.log',
      merge_logs: true,
    },
    {
      name: 'rally-manage',
      cwd: './apps/manage',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3002',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/manage-error.log',
      out_file: './logs/manage-out.log',
      merge_logs: true,
    },
    {
      name: 'rally-admin',
      cwd: './apps/admin',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3003',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      merge_logs: true,
    },
    {
      name: 'rally-portal',
      cwd: './apps/portal',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3004',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/portal-error.log',
      out_file: './logs/portal-out.log',
      merge_logs: true,
    },
  ],
};
